name: window_lockable
description: "The window_lockable is helpful when you want to fix the window size in a Windows application."
version: 1.0.0
homepage: https://github.com/kihyun1998/window_lockable

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: WindowLockablePluginCApi